/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theoriegraphes;

import metier.Configuration;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Label;


public class MenuInitial extends javax.swing.JPanel {
	
	private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;

    /**
     * Creates new form MenuInitial
     */
    public MenuInitial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	 jLayeredPane1 = new javax.swing.JLayeredPane();
         jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
         
         JPanel panel = new JPanel();
         

         javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
         jLayeredPane1Layout.setHorizontalGroup(
         	jLayeredPane1Layout.createParallelGroup(Alignment.LEADING)
         		.addGroup(jLayeredPane1Layout.createSequentialGroup()
         			.addContainerGap()
         			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 519, GroupLayout.PREFERRED_SIZE)
         			.addContainerGap(252, Short.MAX_VALUE))
         );
         jLayeredPane1Layout.setVerticalGroup(
         	jLayeredPane1Layout.createParallelGroup(Alignment.LEADING)
         		.addGroup(jLayeredPane1Layout.createSequentialGroup()
         			.addContainerGap()
         			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 296, GroupLayout.PREFERRED_SIZE)
         			.addContainerGap(55, Short.MAX_VALUE))
         );
                         panel.setLayout(null);
                         jToggleButton2 = new javax.swing.JToggleButton();
                         jToggleButton2.setBackground(new Color(234, 141, 141));
                         jToggleButton2.setBounds(250, 130, 132, 25);
                         panel.add(jToggleButton2);
                         
                                 jToggleButton2.setText("Orienté");
                                 jLayeredPane1.setLayer(jToggleButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
                                 jToggleButton1 = new javax.swing.JToggleButton();
                                 jToggleButton1.setBackground(new Color(234, 141, 141));
                                 jToggleButton1.setBounds(250, 166, 132, 25);
                                 panel.add(jToggleButton1);
                                 
                                         jToggleButton1.setText("Pondéré");
                                         jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                                         
                                                 jLayeredPane1.setLayer(jToggleButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
                                 jButton1 = new javax.swing.JButton();
                                 jButton1.setBackground(new Color(30, 174, 152));
                                 jButton1.setBounds(222, 221, 193, 25);
                                 panel.add(jButton1);
                                 jButton1.setForeground(Color.WHITE);
                                 
                                         
                                         jButton1.setText("Cr\u00E9er");
                                         jButton1.addActionListener(new java.awt.event.ActionListener() {
                                             public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                 jButton1ActionPerformed(evt);
                                             }
                                         });
                                         jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
                                         
                                         Label label = new Label("Remarque : ceci est une case \u00E0 cocher, le graph est par defaut sans orientation.");
                                         label.setFont(new Font("Lucida Fax", Font.ITALIC, 13));
                                         label.setForeground(new Color(224, 108, 108));
                                         label.setBounds(0, 73, 480, 22);
                                         
                                         panel.add(label);
                                         
                                         
         jLayeredPane1.setLayout(jLayeredPane1Layout);

         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
         layout.setHorizontalGroup(
         	layout.createParallelGroup(Alignment.TRAILING)
         		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
         			.addComponent(jLayeredPane1, GroupLayout.PREFERRED_SIZE, 727, GroupLayout.PREFERRED_SIZE)
         			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
         layout.setVerticalGroup(
         	layout.createParallelGroup(Alignment.TRAILING)
         		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
         			.addComponent(jLayeredPane1, GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
         			.addContainerGap())
         );
         this.setLayout(layout);
     }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Configuration.oriente = jToggleButton2.isSelected();
         Configuration.pondere = jToggleButton1.isSelected();
         MainFrame.getInstance().setCentrePanel(new Canvas());
         Configuration.checkAlgos();
     }//GEN-LAST:event_jButton1ActionPerformed
}
